### ISSUE TITLE
Add support for identity listing and associated project listing to user page

### ISSUE THREAD

**Issue by JamesPrice76** [flathub/frontend#165]

**Comment by kymckay** [comment]
Fairly straightforward.  Depends on #164

**Comment by kymckay** [comment]
Will need to make fetch requests to the Redis backend for the user's applications' information to display on the userpage. Have clarified that this is fine (since everything else does it statically currently).

CanMay be able to just reuse the ApplicationCollection component on the userpage for rendering/behaviour.

**Comment by kymckay** [comment]
In terms of tracking I think it makes sense to consider this done with #172. Have opened #215 to track follow up work when more identity possibilities are added.
